
name: 发布

on:
  release:
    types: [published]
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: 使用Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: 安装 pnpm
        uses: pnpm/action-setup@v4
      - name: 安装依赖
        run: pnpm install
      - name: 打包
        run: pnpm run release
  npm-publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 发布
        run: npm publish
        env: 
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
  deploy-doc:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 部署doc
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with: 
          branch: gh-pages
          folder: storybook-static
      
       
          
